Pulling the wiki into the repo
mozilla/OpenWPM pull request #716
Opened 2020-07-24 14:14 UTC by vringar

The wiki was horribly out of date since it was never checked out to disk and never updated alongside the code.
This PR aims to change that by moving all files that previously existed as part of wiki into a wiki folder.

2020-09-02 15:19 UTC, vringar commented
@englehardt While the wiki is not perfect, I think getting it into the tree is more important than having it be perfects once it's in there. 
I hope the warning on wiki/Platform-Architecture.md is clear enough, but I'm willing to delete it if you want me to.

2020-09-11 20:56 UTC, englehardt requested changes
I've left some comments on the changes, two additional notes:
1. It seems strange to separate the instrumentation configuration description for the rest of the configuration descriptions. I think we should merge the current `Instrumentation.md` file with the config documentation under `Browser and Platform Configuration` and `Browser Profile Support`. Those three sections cover all the config questions a person may have.
2. Let's place these under the docs folder, rather than create a new `wiki` folder.

2020-09-11 20:56 UTC, englehardt commented on wiki/Available-Commands.md
> +# Available Commands
Aren't all of these commands currently documented in `Instruments.md`? We should drop this page until we have proper docs available.

2020-09-11 20:56 UTC, englehardt commented on wiki/CONTRIBUTING.md
> +* `python -m autopep8 -r --in-place --exclude venv .`
Should this now be updated to black?

2020-09-11 20:56 UTC, englehardt commented on wiki/CONTRIBUTING.md
> +## Troubleshooting
All of these issues may hit a person just trying to install and run OpenWPM? They should be moved back into the main README. I think we can merge them with the other troubleshooting section.

2020-09-11 20:56 UTC, englehardt commented on wiki/CONTRIBUTING.md
> +### Mac OSX
This info is useful just for people trying to run OpenWPM on Mac OSX. We should move back into the main README.

2020-09-11 20:56 UTC, englehardt commented on wiki/Instrumentation-Schema-Documentation.md
> +If you have any questions on any field, please file an issue or ask in the OpenWPM riot channel and we'll
Add a link to the riot channel here.

2020-09-11 20:56 UTC, englehardt commented on wiki/Platform-Architecture.md
> +# !!Warning!!
Should we just delete this?

2020-10-29 02:05 UTC, englehardt approved these changes
Thanks Stefan, great work! I checked through the major changes since the last review and they look great. This is a big step forward in our documentation :)

2020-10-29 18:17 UTC, merged