Separate JS instrument config from table
mozilla/OpenWPM pull request #738
Opened 2020-08-24 21:13 UTC by englehardt

This moves the js instrumentation config to a separate line so it doesn't create a huge and unreadable table. While we'd like to find a better way to output this information in the future, this removes the unnecessary messiness until then.

Closes #733.

2020-08-24 21:16 UTC, englehardt commented
Before (looks particularly bad when the output is wrapped):
```
Keys:
{
  "browser_id": 0,
  "adblock-plus": 1,
  "bot_mitigation": 2,
  "browser": 3,
  "callstack_instrument": 4,
  "cookie_instrument": 5,
  "disconnect": 6,
  "display_mode": 7,
  "donottrack": 8,
  "extension_enabled": 9,
  "ghostery": 10,
  "http_instrument": 11,
  "https-everywhere": 12,
  "js_instrument": 13,
  "js_instrument_settings": 14,
  "navigation_instrument": 15,
  "prefs": 16,
  "random_attributes": 17,
  "recovery_tar": 18,
  "save_content": 19,
  "tp_cookies": 20,
  "tracking-protection": 21,
  "ublock-origin": 22
}

  0  1      2      3        4      5      6      7         8      9     10     11     12     13     14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          15     16    17     18    19     20      21     22
---  -----  -----  -------  -----  -----  -----  --------  -----  ----  -----  -----  -----  -----  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [...]

2020-08-25 10:52 UTC, vringar requested changes

2020-08-25 10:52 UTC, vringar commented on automation/utilities/platform_utils.py
> +    config_str += json.dumps(js_config, indent=2, separators=(',', ': '))
Seeing as the JS config is already a json string we're now getting escaped JSON printed.

2020-08-25 10:52 UTC, vringar commented on automation/utilities/platform_utils.py
> +        js_config[browser_id] = item.pop('js_instrument_settings')
The easy fix for this issue is to change this line to
```suggestion
        js_config[browser_id] = json.loads(item.pop('js_instrument_settings'))
```

2020-08-31 21:58 UTC, birdsarah commented
Thanks for doing this @englehardt

2020-09-07 15:08 UTC, vringar approved these changes

2020-09-07 15:09 UTC, vringar commented
I made one minor change r+ from me.

2020-09-11 13:43 UTC, merged