Fixes #233, removed built-in extensions
mozilla/OpenWPM pull request #754
Opened 2020-09-29 15:47 UTC by Metropass

Removed from `configure_firefox.py`:
`ghostery`
`uBlock Origin`
`https-everywhere`

I also removed the whitespace to save a few bytes. I checked `deploy_browser.py`, `deploy_firefox.py`, and `selenium_firefox.py` just to make sure the removed extensions aren't referenced, but I found nothing.

2020-09-29 20:54 UTC, vringar commented on automation/default_browser_params.json
>      "adblock-plus": false,
Just realizing, that we also have adblock-plus in here. Feel free to delete that as well.

2020-09-30 11:03 UTC, vringar commented
Could you please also delete this entire folder https://github.com/mozilla/OpenWPM/tree/master/automation/DeployBrowsers/firefox_extensions

2020-09-30 11:06 UTC, vringar commented
Also I'm disabling the localstack tests for now, as I can't find a fix. This means you'll have to merge the master branch into your branch once #756 gets merged.

2020-09-30 14:20 UTC, Metropass commented
> 
> 
> Also I'm disabling the localstack tests for now, as I can't find a fix. This means you'll have to merge the master branch into your branch once #756 gets merged.

Noted, will do!

2020-09-30 15:26 UTC, vringar approved these changes

2020-09-30 15:27 UTC, vringar commented
LGTM. Do you have anything you still want to do?

2020-09-30 15:46 UTC, Metropass commented
> 
> 
> LGTM. Do you have anything you still want to do?

In terms of this PR, I think we got everything, but I was wondering if I can assist in issue #743 ? @vringar

2020-09-30 15:59 UTC, vringar requested changes
I just realize we also don't need
https://github.com/mozilla/OpenWPM/blob/2b1a54eff38feebb737abf402382156e7b2a7438/automation/DeployBrowsers/configure_firefox.py#L19-L22
any more.  Which means we should also remove
https://github.com/mozilla/OpenWPM/blob/2b1a54eff38feebb737abf402382156e7b2a7438/automation/DeployBrowsers/configure_firefox.py#L4-L7

2020-09-30 16:00 UTC, vringar commented
Regarding #743 I'd wait a bit to see if the person currently assigned on it responds, but feel free to have a look at it.
If you want to spend more time on OpenWPM in general, I can also go through the issues and ping you on stuff that's interesting.

2020-09-30 16:12 UTC, Metropass commented
> 
> 
> Regarding #743 I'd wait a bit to see if the person currently assigned on it responds, but feel free to have a look at it.
> If you want to spend more time on OpenWPM in general, I can also go through the issues and ping you on stuff that's interesting.

Yeah that'll be great, thank you so much! 😄

2020-09-30 16:20 UTC, Metropass commented
> 
> 
> I just realize we also don't need
> 
> https://github.com/mozilla/OpenWPM/blob/2b1a54eff38feebb737abf402382156e7b2a7438/automation/DeployBrowsers/configure_firefox.py#L19-L22
> 
> any more. Which means we should also remove
> 
> https://github.com/mozilla/OpenWPM/blob/2b1a54eff38feebb737abf402382156e7b2a7438/automation/DeployBrowsers/configure_firefox.py#L4-L7

Noted, I'll take care of that.

2020-09-30 16:28 UTC, vringar approved these changes

2020-09-30 16:49 UTC, merged