Add performace timer
mozilla/OpenWPM pull request #791
Opened 2020-11-12 15:36 UTC by ankushduacodes

fixes #679

2020-11-12 17:30 UTC, ankushduacodes commented
@vringar I have question about core functionality of OpenWPM, if we go to a website lets say `www.youtube.com`, I see that its logging all the files that are being loaded, and all the requests it making and responses its giving.
But I was wondering about what happens  to redirects, Does OpenWPM goes to a redirect if a website wants to send a user to that redirect? or does it block that redirect.
And if it does go to that redirect, then how does it keep track of orginal website that is refering us to that redirect(Using multiple processes?)

2020-11-13 14:40 UTC, vringar requested changes
Could you please also add this field to the [Schema-Documentation](https://github.com/mozilla/OpenWPM/blob/master/docs/Schema-Documentation.md)
The rest looks good :)

2020-11-13 14:50 UTC, vringar commented
> @vringar I have question about core functionality of OpenWPM, if we go to a website lets say `www.youtube.com`, I see that its logging all the files that are being loaded, and all the requests it making and responses its giving.
> But I was wondering about what happens to redirects, Does OpenWPM goes to a redirect if a website wants to send a user to that redirect? or does it block that redirect.
> And if it does go to that redirect, then how does it keep track of orginal website that is refering us to that redirect(Using multiple processes?)
Each CommandSequence needs to specify a `site_url` it wants to visit. Stored here:
https://github.com/mozilla/OpenWPM/blob/65337e0c19dc857f63bbca1b3aa3773a2c49fd42/automation/DataAggregator/schema.sql#L23-L28
In your example this would be `youtube.com`. Once a CommandSequence gets executed it gets a visit_id and a browser_id. All data collected from the execution of that CommandSequence get stored with the same visit_id and browser_id. This includes redirects and anything else the site might do.

2020-11-13 15:37 UTC, vringar requested changes

2020-11-13 15:37 UTC, vringar commented on automation/TaskManager.py
> +                        "duration": time.time_ns() - t1,
Reading this again I noticed, that we discussed saving the time in millisecond, so this needs to be
```suggestion
                        "duration": int((time.time_ns() - t1)/1000000),
```

2020-11-13 15:37 UTC, vringar commented on docs/Schema-Documentation.md
> +| duration       | int64  |          | A timer that logs how long a command took|
Please document that the duration is in milliseconds.

2020-11-13 16:07 UTC, ankushduacodes commented
> In your example this would be `youtube.com`. Once a CommandSequence gets executed it gets a visit_id and a browser_id. All data collected from the execution of that CommandSequence get stored with the same visit_id and browser_id. This includes redirects and anything else the site might do.

But does it actually visit that redirect or does it just logs that this website requested that redirects?

2020-11-16 10:59 UTC, vringar commented
> But does it actually visit that redirect or does it just logs that this website requested that redirects?

It follows the redirects :) Overall OpenWPM tries to behave as much as a "normal" browser as possible.
To see that for yourself, change demo.py to visit `http://github.com/citp/openwpm` and then have a look into the database what gets logged there.

2020-11-16 14:45 UTC, ankushduacodes commented
@vringar Is there a better way to combat these conflicts? I know why these conflicts are here, It's because of the package rename.
Do I just have to abandon this pull request and start a new one?

2020-11-16 15:00 UTC, vringar commented
What I did in my PR was to first move the `automation` folder to `openwpm`, commit that change and then merge the master branch into the PR branch.
Seeing as your changes are quite small I think this should merge without any problems.

2020-11-16 15:06 UTC, ankushduacodes commented
> What I did in my PR was to first move the `automation` folder to `openwpm`, commit that change and then merge the master branch into the PR branch.
> Seeing as your changes are quite small I think this should merge without any problems.

Just so I am understanding it correctly, you are suggesting that I rename my automation folder to openwpm in `add_performance timer` branch and then commit?

2020-11-16 15:42 UTC, vringar commented
Yes, that's my suggestion. This way git can match up the corresponding files more easily which should prevent any merge conflicts.

2020-11-17 01:38 UTC, closed without merging