Module & Imports conformed to PEP8
mozilla/OpenWPM pull request #806
Opened 2020-11-22 20:34 UTC by FukurouMakoto

To handle [Issue #779 ](https://github.com/mozilla/OpenWPM/issues/779).

Modules and their imports have been changed to snake_case.

2020-11-23 02:04 UTC, FukurouMakoto commented
Could use some guidance on why these last two checks are failing; they don't seem to be due to a improper imports from what I'm reading in the error logs.

2020-11-23 13:26 UTC, vringar commented
I'm surprised to see these tests failing seeing as they are working on [our current master branch](https://travis-ci.org/github/mozilla/OpenWPM/builds/745242480). Can you merge the current master into your branch and see if the tests keep failing?

2020-11-23 13:57 UTC, FukurouMakoto commented
> merge the current master into your branch

Will do but would you mind telling me how to do so?
I've tried merging and as well as rebase and git is saying my branch is up to date.

2020-11-23 14:10 UTC, ankushduacodes commented
@vringar I just looked at @FukurouMakoto's master branch, It's up-to-date. I tried running the failed tests locally, they are running fine.
@FukurouMakoto Try running the failed tests locally may be with this command `python -m pytest -vv -s -k test_parse_neterror_integration` just change test name every time `python -m pytest -vv -s -k <TEST_NAME>`

Dont forget to do `cd test` in project directory

2020-11-23 14:50 UTC, vringar commented
> Will do but would you mind telling me how to do so?
> I've tried merging and as well as rebase and git is saying my branch is up to date.

Sorry for not checking that first. I was hoping this could fix these issues.

2020-11-24 14:03 UTC, vringar commented on OpenWPM.code-workspace
> +}
Could you please remove this file and add it to the .gitignore explaining what it is

2020-11-24 14:10 UTC, vringar requested changes
Thank you for all the work you put into this!
Would you mind working on this some more and renaming the things I commented?

2020-11-24 14:10 UTC, vringar commented on openwpm/Commands/browser_commands.py
> +from ..socket_interface import clientsocket
Could you rename `clientsocket` to `ClientSocket`

2020-11-24 14:10 UTC, vringar commented on test/test_webdriver_utils.py
> +            "SELECT command_status, error FROM crawl_history WHERE command = \"<class 'openwpm.Commands.types.GetCommand'>\"",
Could you please change `Commands` to `commands`.

2020-11-24 14:10 UTC, vringar commented on openwpm/DeployBrowsers/deploy_firefox.py
>  from ..Commands.profile_commands import load_profile
Please change `DeployBrowsers` to `deploy_browsers`

2020-11-24 15:31 UTC, vringar requested changes

2020-11-24 15:31 UTC, vringar commented on docs/Using_OpenWPM.md
> +1. Define all required paramters in a type in `openwpm/commands/Types.py`
This should be 
```suggestion
1. Define all required paramters in a type in `openwpm/commands/types.py`  
```
right?

2020-11-24 15:31 UTC, vringar commented on openwpm/mp_logger.py
>  from .socket_interface import serversocket
Can you please turn `serversocket` into `ServerSocket`. Sorry for missing this before.

2020-11-24 16:14 UTC, vringar approved these changes

2020-11-24 16:34 UTC, merged