Release preparations
mozilla/OpenWPM pull request #866
Opened 2021-03-12 18:34 UTC by vringar

2021-03-12 19:56 UTC, englehardt requested changes
Do we have any way of testing the S3 storage providers? We certainly don't want to add back in localstack and they are pretty simple, but I'm wondering what our options are.

2021-03-12 19:56 UTC, englehardt commented on CHANGELOG.md
> +Minor changes:
```suggestion
Additional changes:
```

2021-03-12 19:56 UTC, englehardt commented on openwpm/storage/cloud_storage/s3_storage.py
> +    base_path/visits/table_name in the given bucket.
```suggestion
    S3StructuredProvider will by default store into
    base_path/visits/table_name in the given bucket.
```

I don't think it's necessary to reference old code here.

2021-03-12 19:56 UTC, englehardt commented on openwpm/storage/cloud_storage/s3_storage.py
> +
```suggestion
```

2021-03-12 19:56 UTC, englehardt commented on openwpm/storage/cloud_storage/s3_storage.py
> +    async def shutdown(self) -> None:
Are you sure we want to pass here? This overwrites ArrowProvider's default method which logs an error if there are any unwritten batches. That still seems useful.

I _think_ we can just drop this.

2021-03-15 12:30 UTC, vringar commented on openwpm/storage/cloud_storage/s3_storage.py
> +
```suggestion
```

2021-03-15 12:36 UTC, vringar commented
One option I can think of is to write integration tests that use docker-compose.
We could build on top of what we have in https://github.com/mozilla/openwpm-crawler/tree/master/deployment/local-compose and our local test server to run crawls that write to localstack and then check that the files stored there are identical to the ones served (for content) and that the records contain everything we expect them to.

2021-03-15 14:09 UTC, englehardt commented
> One option I can think of is to write integration tests that use docker-compose.
> We could build on top of what we have in https://github.com/mozilla/openwpm-crawler/tree/master/deployment/local-compose and our local test server to run crawls that write to localstack and then check that the files stored there are identical to the ones served (for content) and that the records contain everything we expect them to.

Localstack has caused us so many issues that I'd prefer to avoid it, even if we're just using their docker container.

> However for now, I'd argue that we are providing users with enough flexibility that they can just use whatever works for them when using s3fs directly and copy paste these arguments into the S3Providers

What do you mean by `and copy paste these arguments into the S3Providers`?

2021-03-15 14:31 UTC, vringar commented
I
> Localstack has caused us so many issues that I'd prefer to avoid it, even if we're just using their docker container.

While I understand that feeling Localstack is the only way known to me that would allow us to test the S3StorageProviders locally

> > However for now, I'd argue that we are providing users with enough flexibility that they can just use whatever works for them when using s3fs directly and copy paste these arguments into the S3Providers
> 
> What do you mean by `and copy paste these arguments into the S3Providers`?

E.g. if a user got `S3FileSystem(key="bla", secret="blub")` to work then they could do `S3StructuredProvider("my_bucket_name", "base_path", key="bla", secret="blub")`, which would be copying and pasting the constructor arguments and since we just forward them, it should still work.

2021-03-16 10:56 UTC, vringar commented
@englehardt it's ready for merge now

2021-03-16 14:02 UTC, englehardt approved these changes

2021-03-16 14:02 UTC, englehardt commented
> @englehardt it's ready for merge now

LGTM, thanks!

2021-03-16 14:23 UTC, merged